use agent_studios_protocol::id::ApprovalId;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::id::{RuntimeInstanceId, RuntimeSessionId};
use crate::lifecycle::RuntimeLifecycleState;

/// Normalized typed event emitted by an external agent runtime session.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RuntimeEventKind {
    /// Session was initialized and started.
    SessionStarted {
        session_id: RuntimeSessionId,
        instance_id: RuntimeInstanceId,
    },
    /// Lifecycle state changed.
    StatusChanged {
        previous_state: RuntimeLifecycleState,
        new_state: RuntimeLifecycleState,
    },
    /// Incremental output text generated by the agent.
    OutputDelta { text: String },
    /// External agent started invoking a tool or command.
    ToolStarted {
        tool_name: String,
        tool_call_id: String,
    },
    /// External agent completed tool invocation.
    ToolCompleted {
        tool_name: String,
        tool_call_id: String,
        duration_ms: u64,
        success: bool,
    },
    /// Interactive human approval requested by the agent.
    ApprovalRequested {
        approval_id: ApprovalId,
        description: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        command: Option<String>,
    },
    /// External agent produced an output artifact.
    ArtifactProduced { logical_name: String, path: String },
    /// Token usage counters updated.
    UsageUpdated {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        prompt_tokens: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        completion_tokens: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        total_tokens: Option<u64>,
    },
    /// Non-fatal diagnostic or log message.
    Diagnostic { level: String, message: String },
    /// Active turn was interrupted.
    Interrupted { reason: String },
    /// Session or task failed with safe error classification.
    Failed { safe_error_summary: String },
    /// Session or task completed successfully.
    Completed {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
    },
    /// Session was stopped/terminated.
    Stopped,
}

/// Envelope for normalized runtime events, carrying monotonic sequence and timestamp for deterministic correlation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuntimeEvent {
    pub session_id: RuntimeSessionId,
    pub sequence: u64,
    pub timestamp: DateTime<Utc>,
    pub kind: RuntimeEventKind,
}

impl RuntimeEvent {
    pub fn new(session_id: RuntimeSessionId, sequence: u64, kind: RuntimeEventKind) -> Self {
        Self {
            session_id,
            sequence,
            timestamp: Utc::now(),
            kind,
        }
    }
}
